<a href="https://colab.research.google.com/github/Olga-Lyt/Analysis_Cafe_Sales/blob/main/EDA_cafe_sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Analysis_Cafe_Sales  

Cafe Sales - Dirty Data for Cleaning Training  

Dirty Cafe Sales Dataset
Overview
The Dirty Cafe Sales dataset contains 10,000 rows of synthetic data representing sales transactions in a cafe. This dataset is intentionally "dirty," with missing values, inconsistent data, and errors introduced to provide a realistic scenario for data cleaning and exploratory data analysis (EDA). It can be used to practice cleaning techniques, data wrangling, and feature engineering.

File Information
File Name: dirty_cafe_sales.csv
Number of Rows: 10,000
Number of Columns: 8

| Column Name | Description | Example Values |
| ----------- | ----------- | -------------- |
| `Transaction ID` | A unique identifier for each transaction. Always present and unique. | `TXN_1234567` |
| `Item` | The name of the item purchased. May contain missing or invalid values (e.g., "ERROR"). | `Coffee`, `Sandwich` |
| `Quantity` | The quantity of the item purchased. May contain missing or invalid values. | `1`, `3`, `UNKNOWN` |
| `Price Per Unit` | The price of a single unit of the item. May contain missing or invalid values. | `2.00`, `4.00` |
| `Total Spent` | The total amount spent on the transaction. Calculated as `Quantity * Price Per Unit`. | `8.00`, `12.00` |
| `Payment Method` | The method of payment used. May contain missing or invalid values (e.g., None, "UNKNOWN"). | `Cash`, `Credit Card` |
| `Location` | The location where the transaction occurred. May contain missing or invalid values. | `In-store`, `Takeaway`
| `Transaction Date` | The date of the transaction. May contain missing or incorrect values. | `2023-01-01` |

In [ ]:
pip install numpy pandas matplotlib

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Loading dataset  
Завантаження датасету

In [ ]:
url = 'https://raw.githubusercontent.com/Olga-Lyt/Analysis_Cafe_Sales/refs/heads/main/data/dirty_cafe_sales.csv'

df_origin = pd.read_csv(url)
df_origin.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [ ]:
df = df_origin.copy()

## Primary diagnosis   
Первинна діагностика

In [ ]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [ ]:
print("Data types (raw):\n")
df.dtypes

Data types (raw):

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

Problem:  
- ` Numeric columns (Quantity, Price Per Unit, Total Spent)  

- ` Date columns (Transaction Date)

In [ ]:
print("Missing values:\n")
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(1)
missing_report = pd.DataFrame({
    'count': missing,
    '%': missing_pct
})
missing_report[missing_report['count'] > 0]

Missing values:

                  count     %
Item                333   3.3
Quantity            138   1.4
Price Per Unit      179   1.8
Total Spent         173   1.7
Payment Method     2579  25.8
Location           3265  32.6
Transaction Date    159   1.6

In [ ]:
print("Unique values:\n")
print("---Item---\n")
display(df['Item'].value_counts(dropna=False))

print("\n---Payment Method---\n")
display(df['Payment Method'].value_counts(dropna=False))

print("\n---Location---\n")
display(df['Location'].value_counts(dropna=False))

Unique values:

---Item---

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64

---Payment Method---

Payment Method
NaN               2579
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

---Location---

Location
NaN         3265
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

In [ ]:
print("Find lines with 'ERROR' or 'UNKNOWN'\n")
#df.isin(['ERROR', 'UNKNOWN']).any()
mask_error = df.isin(['ERROR', 'UNKNOWN']).any(axis=1)
print(f"Lines with 'ERROR', or 'UNKNOWN': {mask_error.sum()}")

Find lines with 'ERROR' or 'UNKNOWN'

Lines with 'ERROR', or 'UNKNOWN': 2845

ДЗ: Замість записати кількість ERROR/UNKNOWN

In [ ]:
print("Find lines with 'ERROR' or 'UNKNOWN'\n")
#df.isin(['ERROR', 'UNKNOWN']).any()
mask_error = df.isin(['ERROR', 'UNKNOWN']).sum()
print(f"Lines with 'ERROR', or 'UNKNOWN': {mask_error.sum()}")

Find lines with 'ERROR' or 'UNKNOWN'

Lines with 'ERROR', or 'UNKNOWN': 3256

## Data cleaning

На цьому етапі робимо копію, якщо не зробили раніше

'df_origin` - оригінальний датасет
'df` - копія датасету

In [ ]:
print("Rename columns:\n")

df.columns = df.columns.str.strip()
df = df.rename(columns={
    'Transaction ID': 'transaction_id',
    'Item': 'item',
    'Quantity': 'quantity',
    'Price Per Unit': 'price_per_unit',
    'Total Spent': 'total_spent',
    'Payment Method': 'payment_method',
    'Location': 'location',
    'Transaction Date': 'transaction_date'

})

print(list(df.columns))

Rename columns:

['transaction_id', 'item', 'quantity', 'price_per_unit', 'total_spent', 'payment_method', 'location', 'transaction_date']

In [ ]:
"  Transaction Date  ".strip().lower().replace(" ", "_")

'transaction_date'

In [ ]:
"  Transaction    Date  ".strip().lower().replace(" ", "_")

'transaction____date'

In [ ]:
"_".join("   Transaction Date   ".lower().split())

'transaction_date'

In [ ]:
df.columns.str.lower().str.replace(" ", "_")

Index(['transaction_id', 'item', 'quantity', 'price_per_unit', 'total_spent',
       'payment_method', 'location', 'transaction_date'],
      dtype='object')

In [ ]:
# 'ERROR'/'UNKNOWN' -> NaN
df.replace(['ERROR', 'UNKNOWN', 'error', 'unknown', ''], np.nan, inplace=True)
df.head()

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

## Змінюємо типи даних

In [ ]:
for col in ['quantity', 'price_per_unit', 'total_spent']:
    df[col] = pd.to_numeric(df[col], errors='coerce')   # якщо дані не числові, то перетворює на null

df.dtypes

transaction_id       object
item                 object
quantity            float64
price_per_unit      float64
total_spent         float64
payment_method       object
location             object
transaction_date     object
dtype: object

In [ ]:
df['transaction_date'] = df_origin['Transaction Date'].copy  # якщо сталася помилка з назвою колонки, то можна взяти дані з оригіналу

In [ ]:
df['transaction_date'] = pd.to_datetime(df['transaction_date'], errors='coerce')   # перетворює дані колонки на дату

df.dtypes

transaction_id              object
item                        object
quantity                   float64
price_per_unit             float64
total_spent                float64
payment_method              object
location                    object
transaction_date    datetime64[ns]
dtype: object

In [39]:
# Витягуємо додаткові часові ознаки, тобто з стовпчика дати формуємо нові показники

df['year'] = df['transaction_date'].dt.year.astype('Int64')
df['month'] = df['transaction_date'].dt.month.astype('Int64')
# df['month'] = df['transaction_date'].dt.month_name()
df['month_name'] = df['transaction_date'].dt.strftime('%B')  # дата відформатована в формат рядка A,a - день  B,b - місяць, Y,y - рік
df['weekday'] = df['transaction_date'].dt.day_name()  #  день тижня
df['week'] = df['transaction_date'].dt.isocalendar().week.astype('Int64')   # № тижня в році
df[['transaction_date', 'year', 'month', 'month_name', 'weekday', 'week']].head()

  transaction_date  year  month month_name    weekday  week
0       2023-09-08  2023      9  September     Friday    36
1       2023-05-16  2023      5        May    Tuesday    20
2       2023-07-19  2023      7       July  Wednesday    29
3       2023-04-27  2023      4      April   Thursday    17
4       2023-06-11  2023      6       June     Sunday    23

In [40]:
# Заповнення значень стовпчика total_spent: total_spent = quantity * price_per_unit
mask_recoverable = (
    df['total_spent'].isna() &
    df['quantity'].notna() &
    df['price_per_unit']. notna()
)

df.loc[mask_recoverable, 'total_spent'] = (
    df.loc[mask_recoverable, 'quantity'] *
    df.loc[mask_recoverable, 'price_per_unit']
)

print(f"Restoring total spent: {mask_recoverable.sum()} string (quantity * price_per_unit) ")

Restoring total spent: 462 string (quantity * price_per_unit)

In [42]:
df.head()

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date,year,month,month_name,weekday,week
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,2023,9,September,Friday,36
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,2023,5,May,Tuesday,20
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19,2023,7,July,Wednesday,29
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27,2023,4,April,Thursday,17
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,2023,6,June,Sunday,23

In [49]:
price_map = (
    df.dropna(subset=['item', 'price_per_unit'])
    .groupby('item')['price_per_unit']
    .median()
    .to_dict()
)

mask_price = df['price_per_unit'].isna() & df['item'].notna()

df.loc[mask_price, 'price_per_unit'] = df.loc[mask_price, 'item'].map(price_map)  # пошук та заміна значень через loc

print(f"Restoring price_per_unit: {mask_price.sum()} string (median per item) ")

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date,year,month,month_name,weekday,week
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,2023,9,September,Friday,36
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,2023,5,May,Tuesday,20
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19,2023,7,July,Wednesday,29
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27,2023,4,April,Thursday,17
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,2023,6,June,Sunday,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,NaN,2023-08-30,2023,8,August,Wednesday,35
9996,TXN_9659401,NaN,3.0,NaN,3.0,Digital Wallet,NaN,2023-06-02,2023,6,June,Friday,22
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02,2023,3,March,Thursday,9
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,NaN,2023-12-02,2023,12,December,Saturday,48
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07,2023,11,November,Tuesday,45

In [50]:
# Заповнення значень стовпчика total_spent виходячи з нових значень ціни: total_spent = quantity * new_price_per_unit
mask_recoverable2 = (
    df['total_spent'].isna() &
    df['quantity'].notna() &
    df['price_per_unit']. notna()
)

df.loc[mask_recoverable2, 'total_spent'] = (
    df.loc[mask_recoverable2, 'quantity'] *
    df.loc[mask_recoverable2, 'price_per_unit']
)

print(f"Restoring total spent: {mask_recoverable2.sum()} string (new price - median item) ")

Restoring total spent: 17 string (new price - median item)

In [53]:
# Заповнюємо стовпчик item найпопулярнішим товаром mode_item
mode_item = df['item'].mode()[0]
# df['item'].fillna(mode_item, inplace=True)   # застарілий варіант
df.fillna({'item': mode_item}, inplace=True)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              10000 non-null  object
 2   quantity          9521 non-null   float64
 3   price_per_unit    9946 non-null   float64
 4   total_spent       9977 non-null   float64
 5   payment_method    6822 non-null   object
 6   location          6039 non-null   object
 7   transaction_date  9540 non-null   datetime64[ns]
 8   year              9540 non-null   Int64
 9   month             9540 non-null   Int64
 10  month_name        9540 non-null   object
 11  weekday           9540 non-null   object
 12  week              9540 non-null   Int64
dtypes: Int64(3), datetime64[ns](1), float64(3), object(6)
memory usage: 1.0+ MB

In [57]:
# payment_method та location залишаємо невідомими, тобто заповнюємо Unknown
df.fillna(
    {
        'payment_method': 'Unknown',
        'location': 'Unknown'
    },
    inplace=True
)

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              10000 non-null  object
 2   quantity          9521 non-null   float64
 3   price_per_unit    9946 non-null   float64
 4   total_spent       9977 non-null   float64
 5   payment_method    10000 non-null  object
 6   location          10000 non-null  object
 7   transaction_date  9540 non-null   datetime64[ns]
 8   year              9540 non-null   Int64
 9   month             9540 non-null   Int64
 10  month_name        9540 non-null   object
 11  weekday           9540 non-null   object
 12  week              9540 non-null   Int64
dtypes: Int64(3), datetime64[ns](1), float64(3), object(6)
memory usage: 1.0+ MB

In [59]:
# Видалення transaction_date де замість дати стоїть NaT або NaN
before = len(df)

df.dropna(subset=['transaction_date', 'quantity'], inplace=True)

after = len(df)
print(f"Deleted {before - after} rows")

Deleted 914 rows

In [60]:
df.isna().sum()

transaction_id       0
item                 0
quantity             0
price_per_unit      48
total_spent          3
payment_method       0
location             0
transaction_date     0
year                 0
month                0
month_name           0
weekday              0
week                 0
dtype: int64


Перевірка та при потребі прибирання дублікатів

In [61]:
df.columns

Index(['transaction_id', 'item', 'quantity', 'price_per_unit', 'total_spent',
       'payment_method', 'location', 'transaction_date', 'year', 'month',
       'month_name', 'weekday', 'week'],
      dtype='object')

In [63]:
df[['item', 'quantity', 'price_per_unit', 'total_spent',
       'payment_method', 'location', 'transaction_date', 'year', 'month',
       'month_name', 'weekday', 'week']].duplicated().sum()

np.int64(192)

In [64]:
df.duplicated().sum()

np.int64(0)

In [65]:
df.drop_duplicates(inplace=True)  # видалення дублікатів за необхідності

Перевірка на логічність даних. Вони не повинні бути від'ємними

In [66]:
(df.quantity <= 0).sum()  # 0
(df.price_per_unit <= 0).sum()  # 0
(df.total_spent <= 0).sum()  # 0

np.int64(0)

In [69]:
(df['quantity'].isna() & df['price_per_unit'].isna()).sum()

np.int64(0)